/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seat;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import static seat.main.flight;

/**
 *
 * @author Dell
 */
public class Cancellation extends javax.swing.JFrame {

    /**
     * Creates new form Cancellation
     */
    public Cancellation() {
        setIcon();
        initComponents();
    }

    String seat;

    public String getSeat() {
        return seat;
    }

    public void setSeat(String seat) {
        this.seat = seat;
    }

    public Cancellation(String seat) {
        setIcon();
        initComponents();
        SeatTextShow.setText(seat);
        setSeat(seat);
        PassengerFirstNameTextShow.setText(flight.getSeatFirstName(seat));
        PassengerLastNameTextShow.setText(flight.getSeatLastName(seat));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        PassportNoField = new javax.swing.JTextField();
        PassengerLastNameTextShow = new javax.swing.JLabel();
        PassengerNameText = new javax.swing.JLabel();
        ContinueButton = new javax.swing.JButton();
        WarningText1 = new javax.swing.JLabel();
        OwnerName2 = new javax.swing.JLabel();
        DepartHeader3 = new javax.swing.JLabel();
        OwnerName3 = new javax.swing.JLabel();
        CloseButton = new javax.swing.JButton();
        FirstNameText3 = new javax.swing.JLabel();
        FlightNoHeader1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        SeatTextShow = new javax.swing.JLabel();
        OwnerName = new javax.swing.JLabel();
        PassengerFirstNameTextShow = new javax.swing.JLabel();
        PassengerNameText1 = new javax.swing.JLabel();
        VerticalSeperator1 = new javax.swing.JSeparator();
        Header = new javax.swing.JPanel();
        WelcomeText = new javax.swing.JLabel();
        MainLogo4 = new javax.swing.JLabel();
        MainLogo5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Decibel Airlines Reservation System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        PassportNoField.setFont(new java.awt.Font("Dialog", 0, 18)); // NOI18N
        PassportNoField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PassportNoFieldActionPerformed(evt);
            }
        });
        jPanel1.add(PassportNoField, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 370, 40));

        PassengerLastNameTextShow.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        PassengerLastNameTextShow.setForeground(new java.awt.Color(207, 0, 15));
        PassengerLastNameTextShow.setText("YY");
        jPanel1.add(PassengerLastNameTextShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 250, 40));

        PassengerNameText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PassengerNameText.setForeground(new java.awt.Color(102, 102, 102));
        PassengerNameText.setText("LAST NAME");
        jPanel1.add(PassengerNameText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 130, 140, 12));

        ContinueButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ContinueButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/cancel.png"))); // NOI18N
        ContinueButton.setText("CANCEL BOOKING");
        ContinueButton.setFocusPainted(false);
        ContinueButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContinueButtonActionPerformed(evt);
            }
        });
        jPanel1.add(ContinueButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 250, 210, 60));

        WarningText1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        WarningText1.setForeground(new java.awt.Color(207, 0, 15));
        jPanel1.add(WarningText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 240, 40));

        OwnerName2.setBackground(new java.awt.Color(204, 204, 204));
        OwnerName2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        OwnerName2.setForeground(new java.awt.Color(102, 102, 102));
        OwnerName2.setText("© 2018 Decibel Airlines.");
        jPanel1.add(OwnerName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 210, -1));

        DepartHeader3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        DepartHeader3.setForeground(new java.awt.Color(0, 0, 0));
        DepartHeader3.setText("Booking Cancellation");
        jPanel1.add(DepartHeader3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 390, 50));

        OwnerName3.setBackground(new java.awt.Color(204, 204, 204));
        OwnerName3.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        OwnerName3.setForeground(new java.awt.Color(102, 102, 102));
        OwnerName3.setText("Click \"Cancel Booking\" when sure.");
        jPanel1.add(OwnerName3, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 220, 240, 20));

        CloseButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CloseButton.setText("BACK");
        CloseButton.setFocusPainted(false);
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        jPanel1.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 250, 130, 60));

        FirstNameText3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        FirstNameText3.setForeground(new java.awt.Color(0, 0, 0));
        FirstNameText3.setText("Enter passenger's passport no.");
        jPanel1.add(FirstNameText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 220, 300, 30));

        FlightNoHeader1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader1.setForeground(new java.awt.Color(102, 102, 102));
        FlightNoHeader1.setText("SEAT");
        jPanel1.add(FlightNoHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 40, 20));

        jPanel2.setBackground(new java.awt.Color(207, 0, 15));
        jPanel2.setForeground(new java.awt.Color(207, 0, 15));

        SeatTextShow.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        SeatTextShow.setForeground(new java.awt.Color(255, 255, 255));
        SeatTextShow.setText("XX");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addComponent(SeatTextShow)
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeatTextShow, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 130, 90, 50));

        OwnerName.setBackground(new java.awt.Color(204, 204, 204));
        OwnerName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        OwnerName.setForeground(new java.awt.Color(102, 102, 102));
        OwnerName.setText("Please check the information thoroughly before proceeding the cancellation. This process cannot be undone.");
        jPanel1.add(OwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, 690, -1));

        PassengerFirstNameTextShow.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        PassengerFirstNameTextShow.setForeground(new java.awt.Color(207, 0, 15));
        PassengerFirstNameTextShow.setText("XX");
        jPanel1.add(PassengerFirstNameTextShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 250, 40));

        PassengerNameText1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PassengerNameText1.setForeground(new java.awt.Color(102, 102, 102));
        PassengerNameText1.setText("FIRST NAME");
        jPanel1.add(PassengerNameText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 130, 140, 12));

        VerticalSeperator1.setBackground(new java.awt.Color(0, 0, 0));
        VerticalSeperator1.setForeground(new java.awt.Color(0, 0, 0));
        VerticalSeperator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jPanel1.add(VerticalSeperator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 220, 10, 100));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 910, 380));

        Header.setBackground(new java.awt.Color(207, 0, 15));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        WelcomeText.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(WelcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 20, 40));

        MainLogo4.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo4.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/HeaderMainSlogan.png"))); // NOI18N
        Header.add(MainLogo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 170, 100));

        MainLogo5.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo5.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/HeaderMainLogoTextNew.png"))); // NOI18N
        Header.add(MainLogo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 190, 100));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PassportNoFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PassportNoFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PassportNoFieldActionPerformed

    private void ContinueButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContinueButtonActionPerformed
        String passportNo = PassportNoField.getText();
        if (PassportNoField.getText().isEmpty()) {
            WarningText1.setText("* Passport No. is required");
        } else if (passportNo.equals(flight.getSeatPassportNo(getSeat()))) {
            WarningText1.setText("");
            flight.cancelSeat(getSeat());
            System.out.println("A Seat : " + getSeat() + " has been successfully cancelled.");
            JOptionPane.showMessageDialog(this, "A seat " + getSeat() + " has been successfully cancelled.", "", JOptionPane.PLAIN_MESSAGE);
            this.setVisible(false);
            new main().setVisible(true);
        } else {
            WarningText1.setText("");
            JOptionPane.showMessageDialog(this, "Incorrect Passport No.", "", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ContinueButtonActionPerformed

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        this.setVisible(false);
        new main().setVisible(true);
    }//GEN-LAST:event_CloseButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cancellation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cancellation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton ContinueButton;
    private javax.swing.JLabel DepartHeader3;
    private javax.swing.JLabel FirstNameText3;
    private javax.swing.JLabel FlightNoHeader1;
    private javax.swing.JPanel Header;
    private javax.swing.JLabel MainLogo4;
    private javax.swing.JLabel MainLogo5;
    private javax.swing.JLabel OwnerName;
    private javax.swing.JLabel OwnerName2;
    private javax.swing.JLabel OwnerName3;
    private javax.swing.JLabel PassengerFirstNameTextShow;
    private javax.swing.JLabel PassengerLastNameTextShow;
    private javax.swing.JLabel PassengerNameText;
    private javax.swing.JLabel PassengerNameText1;
    private javax.swing.JTextField PassportNoField;
    private javax.swing.JLabel SeatTextShow;
    private javax.swing.JSeparator VerticalSeperator1;
    private javax.swing.JLabel WarningText1;
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appIcon.png")));
    }
}
