/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seat;

import java.awt.Toolkit;
import java.io.FileWriter;
import java.io.IOException;
import javax.swing.JOptionPane;

/**
 *
 * @author Dell
 */
public class Confirmation extends javax.swing.JFrame {

    /**
     * Creates new form Confirmation
     */
    public Confirmation() {
        setIcon();
        initComponents();
    }

    public Confirmation(String seat, String firstName, String lastName, String passportNo) {
        setIcon();
        initComponents();

        SeatTextShow.setText(seat);
        FirstNameShow.setText(firstName);
        LastNameShow.setText(lastName);
        PassportNoShow.setText(passportNo);
        boardingPassPrinter(seat, firstName, lastName, passportNo); //Save boarding pass as Text File
        main.flight.bookSeat(seat, firstName, lastName, passportNo); //Passing passenger's data to store in Flight class
    }

    public static void boardingPassPrinter(String seat, String firstName, String lastName, String passportNo) {
        try {
            FileWriter w = new FileWriter(seat + "_broadingPass.txt");
            w.write("DECIBEL AIRLINES BOARDING PASS\r\n");  
            w.write("\r\n");
            w.write("Seat :  " + seat + "\r\n");
            w.write("Name :  " + firstName + " " + lastName + "\r\n");
            w.write("Passport No. :  " + passportNo + "\r\n");
            w.write("\r\nPlease remember your data for flight cancellation. \r\n© 2018 Decibel Airlines.");    
            w.close();
        } catch (IOException ex) {
            ex.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Main = new javax.swing.JPanel();
        OwnerName = new javax.swing.JLabel();
        FirstNameShow = new javax.swing.JLabel();
        LastNameShow = new javax.swing.JLabel();
        PassportNoShow = new javax.swing.JLabel();
        FlightNoHeader1 = new javax.swing.JLabel();
        PrintButton = new javax.swing.JButton();
        CloseButton = new javax.swing.JButton();
        OwnerName1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        SeatTextShow = new javax.swing.JLabel();
        FlightNoHeader12 = new javax.swing.JLabel();
        FlightNoHeader10 = new javax.swing.JLabel();
        FlightNo7 = new javax.swing.JLabel();
        FlightNoHeader14 = new javax.swing.JLabel();
        FlightNoHeader15 = new javax.swing.JLabel();
        OriginCountry = new javax.swing.JLabel();
        OriginCode = new javax.swing.JLabel();
        DestinationCountry = new javax.swing.JLabel();
        DestinationCode = new javax.swing.JLabel();
        PlaneIcon = new javax.swing.JLabel();
        FlightNoHeader2 = new javax.swing.JLabel();
        FlightNo1 = new javax.swing.JLabel();
        FlightNo3 = new javax.swing.JLabel();
        OriginCountry4 = new javax.swing.JLabel();
        OriginCountry5 = new javax.swing.JLabel();
        FlightNoHeader16 = new javax.swing.JLabel();
        FlightNo2 = new javax.swing.JLabel();
        FlightNoHeader17 = new javax.swing.JLabel();
        DepartHeader3 = new javax.swing.JLabel();
        MainLogo4 = new javax.swing.JLabel();
        HorizontalSeperator1 = new javax.swing.JSeparator();
        Header = new javax.swing.JPanel();
        WelcomeText = new javax.swing.JLabel();
        FlightNoHeader6 = new javax.swing.JLabel();
        FlightNoHeader7 = new javax.swing.JLabel();
        FlightNoHeader8 = new javax.swing.JLabel();
        MainLogo10 = new javax.swing.JLabel();
        MainLogo11 = new javax.swing.JLabel();
        MainLogo6 = new javax.swing.JLabel();
        MainLogo7 = new javax.swing.JLabel();
        MainLogo5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Decibel Airlines Reservation System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        OwnerName.setBackground(new java.awt.Color(204, 204, 204));
        OwnerName.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        OwnerName.setForeground(new java.awt.Color(102, 102, 102));
        OwnerName.setText("Please remember passport No. for flight cancellation.");
        Main.add(OwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 340, -1));

        FirstNameShow.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        FirstNameShow.setForeground(new java.awt.Color(0, 0, 0));
        FirstNameShow.setText("XXXXXX");
        Main.add(FirstNameShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 150, 380, 40));

        LastNameShow.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        LastNameShow.setForeground(new java.awt.Color(0, 0, 0));
        LastNameShow.setText("XXXXX");
        Main.add(LastNameShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 220, 400, 40));

        PassportNoShow.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        PassportNoShow.setForeground(new java.awt.Color(0, 0, 0));
        PassportNoShow.setText("XXXXXX");
        Main.add(PassportNoShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 290, 390, 40));

        FlightNoHeader1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader1.setForeground(new java.awt.Color(102, 102, 102));
        FlightNoHeader1.setText("SEAT");
        Main.add(FlightNoHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 210, 40, 20));

        PrintButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        PrintButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/save.png"))); // NOI18N
        PrintButton.setText("SAVE AS TEXT FILE");
        PrintButton.setFocusPainted(false);
        PrintButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintButtonActionPerformed(evt);
            }
        });
        Main.add(PrintButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 410, 260, 50));

        CloseButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CloseButton.setText("CLOSE");
        CloseButton.setFocusPainted(false);
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });
        Main.add(CloseButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 410, 260, 50));

        OwnerName1.setBackground(new java.awt.Color(204, 204, 204));
        OwnerName1.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        OwnerName1.setForeground(new java.awt.Color(102, 102, 102));
        OwnerName1.setText("© 2018 Decibel Airlines.");
        Main.add(OwnerName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 490, 210, -1));

        jPanel1.setBackground(new java.awt.Color(207, 0, 15));
        jPanel1.setForeground(new java.awt.Color(207, 0, 15));

        SeatTextShow.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        SeatTextShow.setForeground(new java.awt.Color(255, 255, 255));
        SeatTextShow.setText("XX");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(SeatTextShow)
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(SeatTextShow, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        Main.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 210, 90, 50));

        FlightNoHeader12.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader12.setForeground(new java.awt.Color(102, 102, 102));
        FlightNoHeader12.setText("PASSPORT NO.");
        Main.add(FlightNoHeader12, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 280, 130, 20));

        FlightNoHeader10.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader10.setForeground(new java.awt.Color(102, 102, 102));
        FlightNoHeader10.setText("GATE");
        Main.add(FlightNoHeader10, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 150, -1, 12));

        FlightNo7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        FlightNo7.setForeground(new java.awt.Color(207, 0, 15));
        FlightNo7.setText("4");
        Main.add(FlightNo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 160, -1, 30));

        FlightNoHeader14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader14.setForeground(new java.awt.Color(102, 102, 102));
        FlightNoHeader14.setText("FIRST NAME");
        Main.add(FlightNoHeader14, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 140, 100, 20));

        FlightNoHeader15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader15.setForeground(new java.awt.Color(102, 102, 102));
        FlightNoHeader15.setText("LAST NAME");
        Main.add(FlightNoHeader15, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 210, 100, 20));

        OriginCountry.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        OriginCountry.setForeground(new java.awt.Color(102, 102, 102));
        OriginCountry.setText("Chiang Mai");
        Main.add(OriginCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 110, 90, 20));

        OriginCode.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        OriginCode.setForeground(new java.awt.Color(207, 0, 15));
        OriginCode.setText("BKK");
        Main.add(OriginCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, -1, 35));

        DestinationCountry.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DestinationCountry.setForeground(new java.awt.Color(102, 102, 102));
        DestinationCountry.setText("TO");
        Main.add(DestinationCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 50, -1, 12));

        DestinationCode.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        DestinationCode.setForeground(new java.awt.Color(207, 0, 15));
        DestinationCode.setText("CNX");
        Main.add(DestinationCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 70, -1, 35));

        PlaneIcon.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        PlaneIcon.setForeground(new java.awt.Color(0, 0, 0));
        PlaneIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/black-plane.png"))); // NOI18N
        Main.add(PlaneIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 70, 40, -1));

        FlightNoHeader2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader2.setForeground(new java.awt.Color(102, 102, 102));
        FlightNoHeader2.setText("DATE");
        Main.add(FlightNoHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 150, 80, 12));

        FlightNo1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        FlightNo1.setForeground(new java.awt.Color(207, 0, 15));
        FlightNo1.setText("30 Apr");
        Main.add(FlightNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 160, -1, 30));

        FlightNo3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        FlightNo3.setForeground(new java.awt.Color(207, 0, 15));
        FlightNo3.setText("09:15");
        Main.add(FlightNo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, -1, 30));

        OriginCountry4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        OriginCountry4.setForeground(new java.awt.Color(102, 102, 102));
        OriginCountry4.setText("FROM");
        Main.add(OriginCountry4, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 50, -1, 12));

        OriginCountry5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        OriginCountry5.setForeground(new java.awt.Color(102, 102, 102));
        OriginCountry5.setText("Bangkok");
        Main.add(OriginCountry5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 110, 80, 20));

        FlightNoHeader16.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader16.setForeground(new java.awt.Color(102, 102, 102));
        FlightNoHeader16.setText("TIME");
        Main.add(FlightNoHeader16, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, 90, 12));

        FlightNo2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        FlightNo2.setForeground(new java.awt.Color(207, 0, 15));
        FlightNo2.setText("QF 8");
        Main.add(FlightNo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 220, -1, 40));

        FlightNoHeader17.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader17.setForeground(new java.awt.Color(102, 102, 102));
        FlightNoHeader17.setText("FLIGHT");
        Main.add(FlightNoHeader17, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 210, 70, 20));

        DepartHeader3.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        DepartHeader3.setForeground(new java.awt.Color(0, 0, 0));
        DepartHeader3.setText("Booking Summary");
        Main.add(DepartHeader3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 340, 50));

        MainLogo4.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo4.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/barcode.png"))); // NOI18N
        Main.add(MainLogo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 280, 270, 70));
        Main.add(HorizontalSeperator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, 610, 10));

        getContentPane().add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 730, 530));

        Header.setBackground(new java.awt.Color(207, 0, 15));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        WelcomeText.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(WelcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 20, 40));

        FlightNoHeader6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader6.setForeground(new java.awt.Color(255, 255, 255));
        FlightNoHeader6.setText("CONFIRM");
        Header.add(FlightNoHeader6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 80, 30));

        FlightNoHeader7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader7.setForeground(new java.awt.Color(158, 30, 21));
        FlightNoHeader7.setText("SEATS");
        Header.add(FlightNoHeader7, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 50, 60, 30));

        FlightNoHeader8.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader8.setForeground(new java.awt.Color(158, 30, 21));
        FlightNoHeader8.setText("PASSENGER");
        Header.add(FlightNoHeader8, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 50, 100, 30));

        MainLogo10.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo10.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/circleDisable.png"))); // NOI18N
        Header.add(MainLogo10, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 30, 20, 20));

        MainLogo11.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo11.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/circle.png"))); // NOI18N
        Header.add(MainLogo11, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 20, 20));

        MainLogo6.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo6.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/lines.png"))); // NOI18N
        Header.add(MainLogo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 280, 20));

        MainLogo7.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo7.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/circleDisable.png"))); // NOI18N
        Header.add(MainLogo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 20, 20));

        MainLogo5.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo5.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/HeaderMainLogoTextNew.png"))); // NOI18N
        Header.add(MainLogo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 190, 100));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 730, 100));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        this.setVisible(false);
        new main().setVisible(true);
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void PrintButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintButtonActionPerformed
        PrintButton.setText("SAVED");
        PrintButton.setEnabled(false);
        //JOptionPane.showMessageDialog(this, "Boarding pass has been saved.", "", JOptionPane.PLAIN_MESSAGE);
        System.out.println("#### BOARDING PASS SAVED ####");
    }//GEN-LAST:event_PrintButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Confirmation.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Confirmation().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CloseButton;
    private javax.swing.JLabel DepartHeader3;
    private javax.swing.JLabel DestinationCode;
    private javax.swing.JLabel DestinationCountry;
    private javax.swing.JLabel FirstNameShow;
    private javax.swing.JLabel FlightNo1;
    private javax.swing.JLabel FlightNo2;
    private javax.swing.JLabel FlightNo3;
    private javax.swing.JLabel FlightNo7;
    private javax.swing.JLabel FlightNoHeader1;
    private javax.swing.JLabel FlightNoHeader10;
    private javax.swing.JLabel FlightNoHeader12;
    private javax.swing.JLabel FlightNoHeader14;
    private javax.swing.JLabel FlightNoHeader15;
    private javax.swing.JLabel FlightNoHeader16;
    private javax.swing.JLabel FlightNoHeader17;
    private javax.swing.JLabel FlightNoHeader2;
    private javax.swing.JLabel FlightNoHeader6;
    private javax.swing.JLabel FlightNoHeader7;
    private javax.swing.JLabel FlightNoHeader8;
    private javax.swing.JPanel Header;
    private javax.swing.JSeparator HorizontalSeperator1;
    private javax.swing.JLabel LastNameShow;
    private javax.swing.JPanel Main;
    private javax.swing.JLabel MainLogo10;
    private javax.swing.JLabel MainLogo11;
    private javax.swing.JLabel MainLogo4;
    private javax.swing.JLabel MainLogo5;
    private javax.swing.JLabel MainLogo6;
    private javax.swing.JLabel MainLogo7;
    private javax.swing.JLabel OriginCode;
    private javax.swing.JLabel OriginCountry;
    private javax.swing.JLabel OriginCountry4;
    private javax.swing.JLabel OriginCountry5;
    private javax.swing.JLabel OwnerName;
    private javax.swing.JLabel OwnerName1;
    private javax.swing.JLabel PassportNoShow;
    private javax.swing.JLabel PlaneIcon;
    private javax.swing.JButton PrintButton;
    private javax.swing.JLabel SeatTextShow;
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appIcon.png")));
    }
}
