/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package seat;

import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JButton;

/**
 *
 * @author Dell
 */
public class main extends javax.swing.JFrame {

    /**
     * Creates new form main
     */
    public static Flight flight = new Flight();

    public main() {
        initComponents();
        setIcon();
        summaryText();
        seatMapShowAvailable();
        
        String aboutUnderlined = "<html><u>About</u></html>";
        AboutText.setText(aboutUnderlined);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Header = new javax.swing.JPanel();
        WelcomeText = new javax.swing.JLabel();
        FlightNoHeader5 = new javax.swing.JLabel();
        FlightNoHeader6 = new javax.swing.JLabel();
        FlightNoHeader7 = new javax.swing.JLabel();
        MainLogo5 = new javax.swing.JLabel();
        MainLogo7 = new javax.swing.JLabel();
        MainLogo8 = new javax.swing.JLabel();
        MainLogo6 = new javax.swing.JLabel();
        MainLogo9 = new javax.swing.JLabel();
        Main = new javax.swing.JPanel();
        VerticalSeperator1 = new javax.swing.JSeparator();
        DepartHeader = new javax.swing.JLabel();
        FlightNo = new javax.swing.JLabel();
        OriginCountry = new javax.swing.JLabel();
        OriginCode = new javax.swing.JLabel();
        DestinationCountry = new javax.swing.JLabel();
        DestinationCode = new javax.swing.JLabel();
        PlaneIcon = new javax.swing.JLabel();
        HorizontalSeperator1 = new javax.swing.JSeparator();
        WorkingModeHeader = new javax.swing.JLabel();
        BookingButton = new javax.swing.JButton();
        CancelButton = new javax.swing.JButton();
        ViewAllDataButton = new javax.swing.JButton();
        AvailableTextShow = new javax.swing.JLabel();
        ReservedTextShow = new javax.swing.JLabel();
        OwnerName = new javax.swing.JLabel();
        LeftDoor = new javax.swing.JPanel();
        RightDoor = new javax.swing.JPanel();
        Row1 = new javax.swing.JLabel();
        Row2 = new javax.swing.JLabel();
        Row3 = new javax.swing.JLabel();
        Row4 = new javax.swing.JLabel();
        Row5 = new javax.swing.JLabel();
        Row6 = new javax.swing.JLabel();
        Row7 = new javax.swing.JLabel();
        A1 = new javax.swing.JButton();
        B1 = new javax.swing.JButton();
        C1 = new javax.swing.JButton();
        D1 = new javax.swing.JButton();
        E1 = new javax.swing.JButton();
        F1 = new javax.swing.JButton();
        A2 = new javax.swing.JButton();
        B2 = new javax.swing.JButton();
        C2 = new javax.swing.JButton();
        D2 = new javax.swing.JButton();
        E2 = new javax.swing.JButton();
        F2 = new javax.swing.JButton();
        A3 = new javax.swing.JButton();
        B3 = new javax.swing.JButton();
        C3 = new javax.swing.JButton();
        D3 = new javax.swing.JButton();
        E3 = new javax.swing.JButton();
        F3 = new javax.swing.JButton();
        A4 = new javax.swing.JButton();
        B4 = new javax.swing.JButton();
        C4 = new javax.swing.JButton();
        D4 = new javax.swing.JButton();
        E4 = new javax.swing.JButton();
        F4 = new javax.swing.JButton();
        A5 = new javax.swing.JButton();
        B5 = new javax.swing.JButton();
        C5 = new javax.swing.JButton();
        D5 = new javax.swing.JButton();
        E5 = new javax.swing.JButton();
        F5 = new javax.swing.JButton();
        A6 = new javax.swing.JButton();
        B6 = new javax.swing.JButton();
        C6 = new javax.swing.JButton();
        D6 = new javax.swing.JButton();
        E6 = new javax.swing.JButton();
        F6 = new javax.swing.JButton();
        A7 = new javax.swing.JButton();
        B7 = new javax.swing.JButton();
        C7 = new javax.swing.JButton();
        D7 = new javax.swing.JButton();
        E7 = new javax.swing.JButton();
        F7 = new javax.swing.JButton();
        LeftExit = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        RightExit = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        Toilet = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        Toilet1 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        FlightNoHeader2 = new javax.swing.JLabel();
        FlightNoHeader1 = new javax.swing.JLabel();
        FlightNo1 = new javax.swing.JLabel();
        FlightNoHeader3 = new javax.swing.JLabel();
        FlightNo3 = new javax.swing.JLabel();
        AvailableText1 = new javax.swing.JLabel();
        DepartHeader1 = new javax.swing.JLabel();
        OriginCountry1 = new javax.swing.JLabel();
        OriginCountry2 = new javax.swing.JLabel();
        FlightNoHeader4 = new javax.swing.JLabel();
        FlightNo4 = new javax.swing.JLabel();
        DepartHeader2 = new javax.swing.JLabel();
        ReservedText3 = new javax.swing.JLabel();
        AboutText = new javax.swing.JLabel();
        MainLogo2 = new javax.swing.JLabel();
        OwnerName2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Decibel Airlines Reservation System");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Header.setBackground(new java.awt.Color(207, 0, 15));
        Header.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        WelcomeText.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        WelcomeText.setForeground(new java.awt.Color(255, 255, 255));
        Header.add(WelcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 20, 40));

        FlightNoHeader5.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader5.setForeground(new java.awt.Color(158, 30, 21));
        FlightNoHeader5.setText("CONFIRM");
        Header.add(FlightNoHeader5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 50, 80, 30));

        FlightNoHeader6.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader6.setForeground(new java.awt.Color(255, 255, 255));
        FlightNoHeader6.setText("SEATS");
        Header.add(FlightNoHeader6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 50, 60, 30));

        FlightNoHeader7.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader7.setForeground(new java.awt.Color(158, 30, 21));
        FlightNoHeader7.setText("PASSENGER");
        Header.add(FlightNoHeader7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 50, 100, 30));

        MainLogo5.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo5.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/circleDisable.png"))); // NOI18N
        Header.add(MainLogo5, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 30, 20, 20));

        MainLogo7.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo7.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/circleDisable.png"))); // NOI18N
        Header.add(MainLogo7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, 20, 20));

        MainLogo8.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo8.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/circle.png"))); // NOI18N
        Header.add(MainLogo8, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 30, 20, 20));

        MainLogo6.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo6.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/lines.png"))); // NOI18N
        Header.add(MainLogo6, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 280, 20));

        MainLogo9.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo9.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/HeaderMainLogoTextNew.png"))); // NOI18N
        Header.add(MainLogo9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 190, 100));

        getContentPane().add(Header, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 910, 100));

        Main.setBackground(new java.awt.Color(255, 255, 255));
        Main.setForeground(new java.awt.Color(255, 255, 255));
        Main.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        VerticalSeperator1.setBackground(new java.awt.Color(0, 0, 0));
        VerticalSeperator1.setForeground(new java.awt.Color(0, 0, 0));
        VerticalSeperator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        Main.add(VerticalSeperator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 10, 620));

        DepartHeader.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        DepartHeader.setForeground(new java.awt.Color(0, 0, 0));
        DepartHeader.setText("Select Seat");
        Main.add(DepartHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 30, 200, 50));

        FlightNo.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        FlightNo.setForeground(new java.awt.Color(207, 0, 15));
        FlightNo.setText("QF 8");
        Main.add(FlightNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 50, -1, 30));

        OriginCountry.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        OriginCountry.setForeground(new java.awt.Color(102, 102, 102));
        OriginCountry.setText("Chiang Mai");
        Main.add(OriginCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 160, 90, 20));

        OriginCode.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        OriginCode.setForeground(new java.awt.Color(207, 0, 15));
        OriginCode.setText("BKK");
        Main.add(OriginCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, 35));

        DestinationCountry.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        DestinationCountry.setForeground(new java.awt.Color(102, 102, 102));
        DestinationCountry.setText("TO");
        Main.add(DestinationCountry, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, -1, 12));

        DestinationCode.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        DestinationCode.setForeground(new java.awt.Color(207, 0, 15));
        DestinationCode.setText("CNX");
        Main.add(DestinationCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 120, -1, 35));

        PlaneIcon.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        PlaneIcon.setForeground(new java.awt.Color(0, 0, 0));
        PlaneIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/black-plane.png"))); // NOI18N
        Main.add(PlaneIcon, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 120, 40, -1));
        Main.add(HorizontalSeperator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 250, 10));

        WorkingModeHeader.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        WorkingModeHeader.setForeground(new java.awt.Color(0, 0, 0));
        WorkingModeHeader.setText("Booking");
        Main.add(WorkingModeHeader, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 170, -1));

        BookingButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        BookingButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/booking.png"))); // NOI18N
        BookingButton.setText("BOOK");
        BookingButton.setEnabled(false);
        BookingButton.setFocusPainted(false);
        BookingButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookingButtonActionPerformed(evt);
            }
        });
        Main.add(BookingButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 350, 120, 50));

        CancelButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        CancelButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/cancel.png"))); // NOI18N
        CancelButton.setText("CANCEL");
        CancelButton.setFocusPainted(false);
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        Main.add(CancelButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 350, 130, 50));

        ViewAllDataButton.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ViewAllDataButton.setText("VIEW ALL PASSENGER DATA");
        ViewAllDataButton.setFocusPainted(false);
        ViewAllDataButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ViewAllDataButtonActionPerformed(evt);
            }
        });
        Main.add(ViewAllDataButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 540, 260, 50));

        AvailableTextShow.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        AvailableTextShow.setForeground(new java.awt.Color(0, 0, 0));
        AvailableTextShow.setText("XX");
        Main.add(AvailableTextShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 500, 50, -1));

        ReservedTextShow.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        ReservedTextShow.setForeground(new java.awt.Color(0, 0, 0));
        ReservedTextShow.setText("YY");
        Main.add(ReservedTextShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 500, 50, -1));

        OwnerName.setBackground(new java.awt.Color(204, 204, 204));
        OwnerName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        OwnerName.setForeground(new java.awt.Color(102, 102, 102));
        OwnerName.setText("* The seat plan is for guidance only and not true to scale.");
        Main.add(OwnerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 640, 320, 30));

        javax.swing.GroupLayout LeftDoorLayout = new javax.swing.GroupLayout(LeftDoor);
        LeftDoor.setLayout(LeftDoorLayout);
        LeftDoorLayout.setHorizontalGroup(
            LeftDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        LeftDoorLayout.setVerticalGroup(
            LeftDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Main.add(LeftDoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 100, 180, 10));

        javax.swing.GroupLayout RightDoorLayout = new javax.swing.GroupLayout(RightDoor);
        RightDoor.setLayout(RightDoorLayout);
        RightDoorLayout.setHorizontalGroup(
            RightDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 180, Short.MAX_VALUE)
        );
        RightDoorLayout.setVerticalGroup(
            RightDoorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        Main.add(RightDoor, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 100, -1, -1));

        Row1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row1.setForeground(new java.awt.Color(204, 204, 204));
        Row1.setText("1");
        Main.add(Row1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 130, 30, 40));

        Row2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row2.setForeground(new java.awt.Color(204, 204, 204));
        Row2.setText("2");
        Main.add(Row2, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 190, 30, 40));

        Row3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row3.setForeground(new java.awt.Color(204, 204, 204));
        Row3.setText("3");
        Main.add(Row3, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 250, 30, 40));

        Row4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row4.setForeground(new java.awt.Color(204, 204, 204));
        Row4.setText("4");
        Main.add(Row4, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 320, 30, 40));

        Row5.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row5.setForeground(new java.awt.Color(204, 204, 204));
        Row5.setText("5");
        Main.add(Row5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 390, 30, 40));

        Row6.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row6.setForeground(new java.awt.Color(204, 204, 204));
        Row6.setText("6");
        Main.add(Row6, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 450, 30, 40));

        Row7.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        Row7.setForeground(new java.awt.Color(204, 204, 204));
        Row7.setText("7");
        Main.add(Row7, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 30, 40));

        A1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A1.setText("A");
        A1.setFocusPainted(false);
        A1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A1ActionPerformed(evt);
            }
        });
        Main.add(A1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 120, 60, 60));

        B1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B1.setText("B");
        B1.setFocusPainted(false);
        B1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B1ActionPerformed(evt);
            }
        });
        Main.add(B1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 120, 60, 60));

        C1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C1.setText("C");
        C1.setFocusPainted(false);
        C1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C1ActionPerformed(evt);
            }
        });
        Main.add(C1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 120, 60, 60));

        D1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D1.setText("D");
        D1.setFocusPainted(false);
        D1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D1ActionPerformed(evt);
            }
        });
        Main.add(D1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 120, 60, 60));

        E1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E1.setText("E");
        E1.setFocusPainted(false);
        E1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1ActionPerformed(evt);
            }
        });
        Main.add(E1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, 60, 60));

        F1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F1.setText("F");
        F1.setFocusPainted(false);
        F1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F1ActionPerformed(evt);
            }
        });
        Main.add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 120, 60, 60));

        A2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A2.setText("A");
        A2.setFocusPainted(false);
        A2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A2ActionPerformed(evt);
            }
        });
        Main.add(A2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, 60, 60));

        B2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B2.setText("B");
        B2.setFocusPainted(false);
        B2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B2ActionPerformed(evt);
            }
        });
        Main.add(B2, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 60, 60));

        C2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C2.setText("C");
        C2.setFocusPainted(false);
        C2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C2ActionPerformed(evt);
            }
        });
        Main.add(C2, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 60, 60));

        D2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D2.setText("D");
        D2.setFocusPainted(false);
        D2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D2ActionPerformed(evt);
            }
        });
        Main.add(D2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 180, 60, 60));

        E2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E2.setText("E");
        E2.setFocusPainted(false);
        E2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2ActionPerformed(evt);
            }
        });
        Main.add(E2, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 180, 60, 60));

        F2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F2.setText("F");
        F2.setFocusPainted(false);
        F2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F2ActionPerformed(evt);
            }
        });
        Main.add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 180, 60, 60));

        A3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A3.setText("A");
        A3.setFocusPainted(false);
        A3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A3ActionPerformed(evt);
            }
        });
        Main.add(A3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, 60, 60));

        B3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B3.setText("B");
        B3.setFocusPainted(false);
        B3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B3ActionPerformed(evt);
            }
        });
        Main.add(B3, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 60, 60));

        C3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C3.setText("C");
        C3.setFocusPainted(false);
        C3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C3ActionPerformed(evt);
            }
        });
        Main.add(C3, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 240, 60, 60));

        D3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D3.setText("D");
        D3.setFocusPainted(false);
        D3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D3ActionPerformed(evt);
            }
        });
        Main.add(D3, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 240, 60, 60));

        E3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E3.setText("E");
        E3.setFocusPainted(false);
        E3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3ActionPerformed(evt);
            }
        });
        Main.add(E3, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 240, 60, 60));

        F3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F3.setText("F");
        F3.setFocusPainted(false);
        F3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F3ActionPerformed(evt);
            }
        });
        Main.add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 240, 60, 60));

        A4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A4.setText("A");
        A4.setFocusPainted(false);
        A4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A4ActionPerformed(evt);
            }
        });
        Main.add(A4, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 310, 60, 60));

        B4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B4.setText("B");
        B4.setFocusPainted(false);
        B4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B4ActionPerformed(evt);
            }
        });
        Main.add(B4, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 310, 60, 60));

        C4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C4.setText("C");
        C4.setFocusPainted(false);
        C4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C4ActionPerformed(evt);
            }
        });
        Main.add(C4, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 310, 60, 60));

        D4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D4.setText("D");
        D4.setFocusPainted(false);
        D4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D4ActionPerformed(evt);
            }
        });
        Main.add(D4, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 60, 60));

        E4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E4.setText("E");
        E4.setFocusPainted(false);
        E4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E4ActionPerformed(evt);
            }
        });
        Main.add(E4, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 310, 60, 60));

        F4.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F4.setText("F");
        F4.setFocusPainted(false);
        F4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F4ActionPerformed(evt);
            }
        });
        Main.add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 310, 60, 60));

        A5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A5.setText("A");
        A5.setFocusPainted(false);
        A5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A5ActionPerformed(evt);
            }
        });
        Main.add(A5, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, 60, 60));

        B5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B5.setText("B");
        B5.setFocusPainted(false);
        B5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B5ActionPerformed(evt);
            }
        });
        Main.add(B5, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 380, 60, 60));

        C5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C5.setText("C");
        C5.setFocusPainted(false);
        C5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C5ActionPerformed(evt);
            }
        });
        Main.add(C5, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 380, 60, 60));

        D5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D5.setText("D");
        D5.setFocusPainted(false);
        D5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D5ActionPerformed(evt);
            }
        });
        Main.add(D5, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 380, 60, 60));

        E5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E5.setText("E");
        E5.setFocusPainted(false);
        E5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E5ActionPerformed(evt);
            }
        });
        Main.add(E5, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 380, 60, 60));

        F5.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F5.setText("F");
        F5.setFocusPainted(false);
        F5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F5ActionPerformed(evt);
            }
        });
        Main.add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 380, 60, 60));

        A6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A6.setText("A");
        A6.setFocusPainted(false);
        A6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A6ActionPerformed(evt);
            }
        });
        Main.add(A6, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, 60, 60));

        B6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B6.setText("B");
        B6.setFocusPainted(false);
        B6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B6ActionPerformed(evt);
            }
        });
        Main.add(B6, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 440, 60, 60));

        C6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C6.setText("C");
        C6.setFocusPainted(false);
        C6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C6ActionPerformed(evt);
            }
        });
        Main.add(C6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 440, 60, 60));

        D6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D6.setText("D");
        D6.setFocusPainted(false);
        D6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D6ActionPerformed(evt);
            }
        });
        Main.add(D6, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 440, 60, 60));

        E6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E6.setText("E");
        E6.setFocusPainted(false);
        E6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E6ActionPerformed(evt);
            }
        });
        Main.add(E6, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 440, 60, 60));

        F6.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F6.setText("F");
        F6.setFocusPainted(false);
        F6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F6ActionPerformed(evt);
            }
        });
        Main.add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 440, 60, 60));

        A7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        A7.setText("A");
        A7.setFocusPainted(false);
        A7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                A7ActionPerformed(evt);
            }
        });
        Main.add(A7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, 60, 60));

        B7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        B7.setText("B");
        B7.setFocusPainted(false);
        B7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                B7ActionPerformed(evt);
            }
        });
        Main.add(B7, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 500, 60, 60));

        C7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        C7.setText("C");
        C7.setFocusPainted(false);
        C7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                C7ActionPerformed(evt);
            }
        });
        Main.add(C7, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 500, 60, 60));

        D7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        D7.setText("D");
        D7.setFocusPainted(false);
        D7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                D7ActionPerformed(evt);
            }
        });
        Main.add(D7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 500, 60, 60));

        E7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        E7.setText("E");
        E7.setFocusPainted(false);
        E7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E7ActionPerformed(evt);
            }
        });
        Main.add(E7, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 500, 60, 60));

        F7.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        F7.setText("F");
        F7.setFocusPainted(false);
        F7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                F7ActionPerformed(evt);
            }
        });
        Main.add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 500, 60, 60));

        LeftExit.setBackground(new java.awt.Color(52, 79, 88));

        jLabel13.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(0, 0, 0));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/exit.png"))); // NOI18N

        javax.swing.GroupLayout LeftExitLayout = new javax.swing.GroupLayout(LeftExit);
        LeftExit.setLayout(LeftExitLayout);
        LeftExitLayout.setHorizontalGroup(
            LeftExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftExitLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel13)
                .addContainerGap(8, Short.MAX_VALUE))
        );
        LeftExitLayout.setVerticalGroup(
            LeftExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LeftExitLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        Main.add(LeftExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 30, 60));

        RightExit.setBackground(new java.awt.Color(52, 79, 88));

        jLabel27.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 0, 0));
        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/exit.png"))); // NOI18N

        javax.swing.GroupLayout RightExitLayout = new javax.swing.GroupLayout(RightExit);
        RightExit.setLayout(RightExitLayout);
        RightExitLayout.setHorizontalGroup(
            RightExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightExitLayout.createSequentialGroup()
                .addContainerGap(8, Short.MAX_VALUE)
                .addComponent(jLabel27)
                .addContainerGap())
        );
        RightExitLayout.setVerticalGroup(
            RightExitLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, RightExitLayout.createSequentialGroup()
                .addContainerGap(16, Short.MAX_VALUE)
                .addComponent(jLabel27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        Main.add(RightExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 310, -1, -1));

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 0, 0));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/toilet.png"))); // NOI18N

        javax.swing.GroupLayout ToiletLayout = new javax.swing.GroupLayout(Toilet);
        Toilet.setLayout(ToiletLayout);
        ToiletLayout.setHorizontalGroup(
            ToiletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, ToiletLayout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        ToiletLayout.setVerticalGroup(
            ToiletLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ToiletLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        Main.add(Toilet, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 570, 180, 50));

        jLabel15.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(0, 0, 0));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/toilet.png"))); // NOI18N

        javax.swing.GroupLayout Toilet1Layout = new javax.swing.GroupLayout(Toilet1);
        Toilet1.setLayout(Toilet1Layout);
        Toilet1Layout.setHorizontalGroup(
            Toilet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Toilet1Layout.createSequentialGroup()
                .addContainerGap(75, Short.MAX_VALUE)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36))
        );
        Toilet1Layout.setVerticalGroup(
            Toilet1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Toilet1Layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(11, Short.MAX_VALUE))
        );

        Main.add(Toilet1, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 570, -1, 50));

        FlightNoHeader2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader2.setForeground(new java.awt.Color(102, 102, 102));
        FlightNoHeader2.setText("FLIGHT");
        Main.add(FlightNoHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 40, 70, 12));

        FlightNoHeader1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader1.setForeground(new java.awt.Color(102, 102, 102));
        FlightNoHeader1.setText("DATE");
        Main.add(FlightNoHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 200, 80, 12));

        FlightNo1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        FlightNo1.setForeground(new java.awt.Color(207, 0, 15));
        FlightNo1.setText("30 Apr");
        Main.add(FlightNo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, 30));

        FlightNoHeader3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader3.setForeground(new java.awt.Color(102, 102, 102));
        FlightNoHeader3.setText("TIME");
        Main.add(FlightNoHeader3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 200, 90, 12));

        FlightNo3.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        FlightNo3.setForeground(new java.awt.Color(207, 0, 15));
        FlightNo3.setText("09:15");
        Main.add(FlightNo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, 30));

        AvailableText1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        AvailableText1.setForeground(new java.awt.Color(102, 102, 102));
        AvailableText1.setText("AVAILABLE");
        Main.add(AvailableText1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 480, 90, 30));

        DepartHeader1.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        DepartHeader1.setForeground(new java.awt.Color(0, 0, 0));
        DepartHeader1.setText("Summary");
        Main.add(DepartHeader1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 180, 60));

        OriginCountry1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        OriginCountry1.setForeground(new java.awt.Color(102, 102, 102));
        OriginCountry1.setText("FROM");
        Main.add(OriginCountry1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 12));

        OriginCountry2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        OriginCountry2.setForeground(new java.awt.Color(102, 102, 102));
        OriginCountry2.setText("Bangkok");
        Main.add(OriginCountry2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 80, 20));

        FlightNoHeader4.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        FlightNoHeader4.setForeground(new java.awt.Color(102, 102, 102));
        FlightNoHeader4.setText("ADULT");
        Main.add(FlightNoHeader4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 90, 12));

        FlightNo4.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        FlightNo4.setForeground(new java.awt.Color(207, 0, 15));
        FlightNo4.setText("1");
        Main.add(FlightNo4, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 210, -1, 30));

        DepartHeader2.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        DepartHeader2.setForeground(new java.awt.Color(0, 0, 0));
        DepartHeader2.setText("Depart");
        Main.add(DepartHeader2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 140, 50));

        ReservedText3.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        ReservedText3.setForeground(new java.awt.Color(102, 102, 102));
        ReservedText3.setText("BOOKED");
        Main.add(ReservedText3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 480, 80, 30));

        AboutText.setBackground(new java.awt.Color(204, 204, 204));
        AboutText.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        AboutText.setForeground(new java.awt.Color(102, 102, 102));
        AboutText.setText(" About");
        AboutText.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                AboutTextMouseClicked(evt);
            }
        });
        Main.add(AboutText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 620, 60, 70));

        MainLogo2.setFont(new java.awt.Font("Dialog", 1, 42)); // NOI18N
        MainLogo2.setForeground(new java.awt.Color(255, 255, 255));
        MainLogo2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/seat/about.png"))); // NOI18N
        MainLogo2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                MainLogo2MouseClicked(evt);
            }
        });
        Main.add(MainLogo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 620, 30, 70));

        OwnerName2.setBackground(new java.awt.Color(204, 204, 204));
        OwnerName2.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        OwnerName2.setForeground(new java.awt.Color(102, 102, 102));
        OwnerName2.setText("© 2018 Decibel Airlines.");
        Main.add(OwnerName2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 650, 140, 10));

        getContentPane().add(Main, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 910, 690));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void C1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C1ActionPerformed
        seatButtonSelected("C1");
    }//GEN-LAST:event_C1ActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        seatMapShowBooked();
        BookingButton.setEnabled(true);
        CancelButton.setEnabled(!BookingButton.isEnabled());
        WorkingModeHeader.setText("Canceling");
        System.out.println("CANCELING MODE");
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void BookingButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookingButtonActionPerformed
        seatMapShowAvailable();
        BookingButton.setEnabled(!BookingButton.isEnabled());
        CancelButton.setEnabled(true);
        WorkingModeHeader.setText("Booking");
        System.out.println("BOOKING MODE");
    }//GEN-LAST:event_BookingButtonActionPerformed

    private void A1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A1ActionPerformed
        seatButtonSelected("A1");
    }//GEN-LAST:event_A1ActionPerformed

    private void B1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B1ActionPerformed
        seatButtonSelected("B1");
    }//GEN-LAST:event_B1ActionPerformed

    private void D1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D1ActionPerformed
        seatButtonSelected("D1");
    }//GEN-LAST:event_D1ActionPerformed

    private void E1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1ActionPerformed
        seatButtonSelected("E1");
    }//GEN-LAST:event_E1ActionPerformed

    private void F1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F1ActionPerformed
        seatButtonSelected("F1");
    }//GEN-LAST:event_F1ActionPerformed

    private void A2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A2ActionPerformed
        seatButtonSelected("A2");
    }//GEN-LAST:event_A2ActionPerformed

    private void B2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B2ActionPerformed
        seatButtonSelected("B2");
    }//GEN-LAST:event_B2ActionPerformed

    private void C2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C2ActionPerformed
        seatButtonSelected("C2");
    }//GEN-LAST:event_C2ActionPerformed

    private void D2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D2ActionPerformed
        seatButtonSelected("D2");
    }//GEN-LAST:event_D2ActionPerformed

    private void E2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2ActionPerformed
        seatButtonSelected("E2");
    }//GEN-LAST:event_E2ActionPerformed

    private void F2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F2ActionPerformed
        seatButtonSelected("F2");
    }//GEN-LAST:event_F2ActionPerformed

    private void A3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A3ActionPerformed
        seatButtonSelected("A3");
    }//GEN-LAST:event_A3ActionPerformed

    private void B3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B3ActionPerformed
        seatButtonSelected("B3");
    }//GEN-LAST:event_B3ActionPerformed

    private void C3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C3ActionPerformed
        seatButtonSelected("C3");
    }//GEN-LAST:event_C3ActionPerformed

    private void D3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D3ActionPerformed
        seatButtonSelected("D3");
    }//GEN-LAST:event_D3ActionPerformed

    private void E3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3ActionPerformed
        seatButtonSelected("E3");
    }//GEN-LAST:event_E3ActionPerformed

    private void F3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F3ActionPerformed
        seatButtonSelected("F3");
    }//GEN-LAST:event_F3ActionPerformed

    private void A4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A4ActionPerformed
        seatButtonSelected("A4");
    }//GEN-LAST:event_A4ActionPerformed

    private void B4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B4ActionPerformed
        seatButtonSelected("B4");
    }//GEN-LAST:event_B4ActionPerformed

    private void C4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C4ActionPerformed
        seatButtonSelected("C4");
    }//GEN-LAST:event_C4ActionPerformed

    private void D4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D4ActionPerformed
        seatButtonSelected("D4");
    }//GEN-LAST:event_D4ActionPerformed

    private void E4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E4ActionPerformed
        seatButtonSelected("E4");
    }//GEN-LAST:event_E4ActionPerformed

    private void F4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F4ActionPerformed
        seatButtonSelected("F4");
    }//GEN-LAST:event_F4ActionPerformed

    private void A5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A5ActionPerformed
        seatButtonSelected("A5");
    }//GEN-LAST:event_A5ActionPerformed

    private void B5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B5ActionPerformed
        seatButtonSelected("B5");
    }//GEN-LAST:event_B5ActionPerformed

    private void C5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C5ActionPerformed
        seatButtonSelected("C5");
    }//GEN-LAST:event_C5ActionPerformed

    private void D5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D5ActionPerformed
        seatButtonSelected("D5");
    }//GEN-LAST:event_D5ActionPerformed

    private void E5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E5ActionPerformed
        seatButtonSelected("E5");
    }//GEN-LAST:event_E5ActionPerformed

    private void F5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F5ActionPerformed
        seatButtonSelected("F5");
    }//GEN-LAST:event_F5ActionPerformed

    private void A6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A6ActionPerformed
        seatButtonSelected("A6");
    }//GEN-LAST:event_A6ActionPerformed

    private void B6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B6ActionPerformed
        seatButtonSelected("B6");
    }//GEN-LAST:event_B6ActionPerformed

    private void C6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C6ActionPerformed
        seatButtonSelected("C6");
    }//GEN-LAST:event_C6ActionPerformed

    private void D6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D6ActionPerformed
        seatButtonSelected("D6");
    }//GEN-LAST:event_D6ActionPerformed

    private void E6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E6ActionPerformed
        seatButtonSelected("E6");
    }//GEN-LAST:event_E6ActionPerformed

    private void F6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F6ActionPerformed
        seatButtonSelected("F6");
    }//GEN-LAST:event_F6ActionPerformed

    private void A7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_A7ActionPerformed
        seatButtonSelected("A7");
    }//GEN-LAST:event_A7ActionPerformed

    private void B7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_B7ActionPerformed
        seatButtonSelected("B7");
    }//GEN-LAST:event_B7ActionPerformed

    private void C7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_C7ActionPerformed
        seatButtonSelected("C7");
    }//GEN-LAST:event_C7ActionPerformed

    private void D7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_D7ActionPerformed
        seatButtonSelected("D7");
    }//GEN-LAST:event_D7ActionPerformed

    private void E7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E7ActionPerformed
        seatButtonSelected("E7");
    }//GEN-LAST:event_E7ActionPerformed

    private void F7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_F7ActionPerformed
        seatButtonSelected("F7");
    }//GEN-LAST:event_F7ActionPerformed

    private void ViewAllDataButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ViewAllDataButtonActionPerformed
        new ShowData().setVisible(true);
        System.out.println("PASSENGER SUMMARY LAUNCHED");
        this.setVisible(false);
    }//GEN-LAST:event_ViewAllDataButtonActionPerformed

    private void MainLogo2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_MainLogo2MouseClicked
        new About().setVisible(true);
    }//GEN-LAST:event_MainLogo2MouseClicked

    private void AboutTextMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_AboutTextMouseClicked
        new About().setVisible(true);
    }//GEN-LAST:event_AboutTextMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton A1;
    private javax.swing.JButton A2;
    private javax.swing.JButton A3;
    private javax.swing.JButton A4;
    private javax.swing.JButton A5;
    private javax.swing.JButton A6;
    private javax.swing.JButton A7;
    private javax.swing.JLabel AboutText;
    private javax.swing.JLabel AvailableText1;
    private javax.swing.JLabel AvailableTextShow;
    private javax.swing.JButton B1;
    private javax.swing.JButton B2;
    private javax.swing.JButton B3;
    private javax.swing.JButton B4;
    private javax.swing.JButton B5;
    private javax.swing.JButton B6;
    private javax.swing.JButton B7;
    private javax.swing.JButton BookingButton;
    private javax.swing.JButton C1;
    private javax.swing.JButton C2;
    private javax.swing.JButton C3;
    private javax.swing.JButton C4;
    private javax.swing.JButton C5;
    private javax.swing.JButton C6;
    private javax.swing.JButton C7;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton D1;
    private javax.swing.JButton D2;
    private javax.swing.JButton D3;
    private javax.swing.JButton D4;
    private javax.swing.JButton D5;
    private javax.swing.JButton D6;
    private javax.swing.JButton D7;
    private javax.swing.JLabel DepartHeader;
    private javax.swing.JLabel DepartHeader1;
    private javax.swing.JLabel DepartHeader2;
    private javax.swing.JLabel DestinationCode;
    private javax.swing.JLabel DestinationCountry;
    private javax.swing.JButton E1;
    private javax.swing.JButton E2;
    private javax.swing.JButton E3;
    private javax.swing.JButton E4;
    private javax.swing.JButton E5;
    private javax.swing.JButton E6;
    private javax.swing.JButton E7;
    private javax.swing.JButton F1;
    private javax.swing.JButton F2;
    private javax.swing.JButton F3;
    private javax.swing.JButton F4;
    private javax.swing.JButton F5;
    private javax.swing.JButton F6;
    private javax.swing.JButton F7;
    private javax.swing.JLabel FlightNo;
    private javax.swing.JLabel FlightNo1;
    private javax.swing.JLabel FlightNo3;
    private javax.swing.JLabel FlightNo4;
    private javax.swing.JLabel FlightNoHeader1;
    private javax.swing.JLabel FlightNoHeader2;
    private javax.swing.JLabel FlightNoHeader3;
    private javax.swing.JLabel FlightNoHeader4;
    private javax.swing.JLabel FlightNoHeader5;
    private javax.swing.JLabel FlightNoHeader6;
    private javax.swing.JLabel FlightNoHeader7;
    private javax.swing.JPanel Header;
    private javax.swing.JSeparator HorizontalSeperator1;
    private javax.swing.JPanel LeftDoor;
    private javax.swing.JPanel LeftExit;
    private javax.swing.JPanel Main;
    private javax.swing.JLabel MainLogo2;
    private javax.swing.JLabel MainLogo5;
    private javax.swing.JLabel MainLogo6;
    private javax.swing.JLabel MainLogo7;
    private javax.swing.JLabel MainLogo8;
    private javax.swing.JLabel MainLogo9;
    private javax.swing.JLabel OriginCode;
    private javax.swing.JLabel OriginCountry;
    private javax.swing.JLabel OriginCountry1;
    private javax.swing.JLabel OriginCountry2;
    private javax.swing.JLabel OwnerName;
    private javax.swing.JLabel OwnerName2;
    private javax.swing.JLabel PlaneIcon;
    private javax.swing.JLabel ReservedText3;
    private javax.swing.JLabel ReservedTextShow;
    private javax.swing.JPanel RightDoor;
    private javax.swing.JPanel RightExit;
    private javax.swing.JLabel Row1;
    private javax.swing.JLabel Row2;
    private javax.swing.JLabel Row3;
    private javax.swing.JLabel Row4;
    private javax.swing.JLabel Row5;
    private javax.swing.JLabel Row6;
    private javax.swing.JLabel Row7;
    private javax.swing.JPanel Toilet;
    private javax.swing.JPanel Toilet1;
    private javax.swing.JSeparator VerticalSeperator1;
    private javax.swing.JButton ViewAllDataButton;
    private javax.swing.JLabel WelcomeText;
    private javax.swing.JLabel WorkingModeHeader;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel27;
    // End of variables declaration//GEN-END:variables

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("appIcon.png")));
    }

    private void summaryText() {
        String availableSeat = Integer.toString(flight.countAvailable());
        String bookedSeat = Integer.toString(42 - flight.countAvailable());
        AvailableTextShow.setText(availableSeat);
        ReservedTextShow.setText(bookedSeat);
    }

    private void seatMapShowAvailable() {
        ArrayList<JButton> seatButton = new ArrayList<JButton>();
        seatButton.add(A1);
        seatButton.add(A2);
        seatButton.add(A3);
        seatButton.add(A4);
        seatButton.add(A5);
        seatButton.add(A6);
        seatButton.add(A7);
        seatButton.add(B1);
        seatButton.add(B2);
        seatButton.add(B3);
        seatButton.add(B4);
        seatButton.add(B5);
        seatButton.add(B6);
        seatButton.add(B7);
        seatButton.add(C1);
        seatButton.add(C2);
        seatButton.add(C3);
        seatButton.add(C4);
        seatButton.add(C5);
        seatButton.add(C6);
        seatButton.add(C7);
        seatButton.add(D1);
        seatButton.add(D2);
        seatButton.add(D3);
        seatButton.add(D4);
        seatButton.add(D5);
        seatButton.add(D6);
        seatButton.add(D7);
        seatButton.add(E1);
        seatButton.add(E2);
        seatButton.add(E3);
        seatButton.add(E4);
        seatButton.add(E5);
        seatButton.add(E6);
        seatButton.add(E7);
        seatButton.add(F1);
        seatButton.add(F2);
        seatButton.add(F3);
        seatButton.add(F4);
        seatButton.add(F5);
        seatButton.add(F6);
        seatButton.add(F7);

        ArrayList<String> seatMap = new ArrayList<String>();
        for (char alph = 'A'; alph <= 'F'; alph++) {
            for (int j = 1; j <= 7; j++) {
                String position = alph + "" + j;
                seatMap.add(position);
            } // create String A1, A2, A3 for passing value
        }

        for (int j = 0; j <= 41; j++) {
            if (flight.getSeatStatus(seatMap.get(j)) == true) {
                (seatButton.get(j)).setEnabled(true);
            } else {
                (seatButton.get(j)).setEnabled(false);
            }
        }
    }

    private void seatMapShowBooked() {
        ArrayList<JButton> seatButton = new ArrayList<JButton>();
        seatButton.add(A1);
        seatButton.add(A2);
        seatButton.add(A3);
        seatButton.add(A4);
        seatButton.add(A5);
        seatButton.add(A6);
        seatButton.add(A7);
        seatButton.add(B1);
        seatButton.add(B2);
        seatButton.add(B3);
        seatButton.add(B4);
        seatButton.add(B5);
        seatButton.add(B6);
        seatButton.add(B7);
        seatButton.add(C1);
        seatButton.add(C2);
        seatButton.add(C3);
        seatButton.add(C4);
        seatButton.add(C5);
        seatButton.add(C6);
        seatButton.add(C7);
        seatButton.add(D1);
        seatButton.add(D2);
        seatButton.add(D3);
        seatButton.add(D4);
        seatButton.add(D5);
        seatButton.add(D6);
        seatButton.add(D7);
        seatButton.add(E1);
        seatButton.add(E2);
        seatButton.add(E3);
        seatButton.add(E4);
        seatButton.add(E5);
        seatButton.add(E6);
        seatButton.add(E7);
        seatButton.add(F1);
        seatButton.add(F2);
        seatButton.add(F3);
        seatButton.add(F4);
        seatButton.add(F5);
        seatButton.add(F6);
        seatButton.add(F7);

        ArrayList<String> seatMap = new ArrayList<String>();
        for (char alph = 'A'; alph <= 'F'; alph++) {
            for (int j = 1; j <= 7; j++) {
                String position = alph + "" + j;
                seatMap.add(position);
            } // create String A1, A2, A3 for passing value
        }

        for (int j = 0; j <= 41; j++) {
            if (flight.getSeatStatus(seatMap.get(j)) == true) {
                (seatButton.get(j)).setEnabled(false);
            } else {
                (seatButton.get(j)).setEnabled(true);
            }
        }
    }

    public void seatButtonSelected(String buttonSelected) {
        String position = buttonSelected;
        if (this.flight.getSeatStatus(position) == true) { //Seat is available
            System.out.println("BOOKING process of " + position + " starred.");
            new RegisterForm(position).setVisible(true); //Passing seat to RegisterForm
            this.setVisible(false);
        } else {
            System.out.println("CANCELING process of " + position + " started.");
            new Cancellation(position).setVisible(true);
            this.setVisible(false);
        }
    }
}
